# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e470b7c1e94561fe22651d869a9a79a04357363f60925ccdc307dc07b69bed7c1e6a7743f2cf5f1b61090da618537437c3d1d3095cad128f9f00dc0e2d9b6b19

test:
  secret_key_base: 65376b7aea69983b921cb35cd6ec57e9b1f899381d85ce0132443fb45b75d02163c453a499957a9198a565a5c0638e762fac1bb87e2f16fd062992e2f4e11d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
